wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: HTGN
dataset:
  desc: null
  value: enron
time granularity:
  desc: null
  value: monthly
_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711116483.552015
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
